import type { components } from "./types";

type S = components["schemas"];

export type LiveState = S["LiveStateOut"];
export type EnergySnapshot = S["EnergySnapshot"];
export type Measurement = S["Measurement"];
export type BufferState = S["BufferState"];
export type HeatPumpState = S["HeatPumpState"];
export type Decision = S["Decision"];
export type OperatingMode = S["OperatingMode"];
export type Plan = S["PlanOut"];
export type PlanInterval = S["PlanIntervalOut"];
export type PriceWindow = S["PriceWindowOut"];
export type History = S["HistoryOut"];
export type HistoryRow = Record<string, number | string | null>;
export type ActuatorCommandOut = S["ActuatorCommandOut"];
export type HeatPumpModeIn = S["HeatPumpModeIn"];
export type SystemMode = S["SystemMode"];
export type AutoProfile = S["AutoProfile"];
export type Quality = S["Quality"];
export type ForecastEvaluation = S["ForecastEvaluationOut"];
export type ForecastDay = S["ForecastDayOut"];
export type ForecastPoint = S["ForecastPointOut"];
export type DailyScore = S["DailyScoreOut"];
export type HorizonScore = S["HorizonScoreOut"];
export type ForecastScore = S["ForecastScore"];
export type CorrectorState = S["CorrectorState"];
export type EnergySummary = S["EnergySummaryOut"];
export type EnergyBucket = S["EnergyBucketOut"];
export type EnergyTotals = S["EnergyTotalsOut"];
export type HeatReport = S["HeatReportOut"];
export type HeatForecastPoint = S["HeatForecastPoint"];
export type EvReport = S["EvReportOut"];
export type EvSession = S["EvSessionOut"];
export type Period = S["EnergySummaryOut"]["period"];
