/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Gesundheitszustand */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/live/state": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Aktueller Zustand */
        get: operations["state_api_v1_live_state_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/live/stream": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Server-Sent Events: snapshot, decision, plan, system */
        get: operations["stream_api_v1_live_stream_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/history": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Minutenmittel eines Zeitraums */
        get: operations["history_api_v1_history_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/plan": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Aktueller Energieplan (Fenster und 15-min-Raster) */
        get: operations["plan_api_v1_plan_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/forecast/evaluation": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Prognose gegen Ist, Tageskennzahlen, Korrekturfaktoren und was sich ändert */
        get: operations["evaluation_api_v1_forecast_evaluation_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/energy/summary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Energiebilanz eines Zeitraums */
        get: operations["summary_api_v1_energy_summary_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/energy/heat": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Wärme: WP-Strom, Kosten, Wärmebedarfsprognose */
        get: operations["heat_api_v1_energy_heat_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/energy/ev": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Wallbox: Ladeenergie, Herkunft, Kosten, Ladevorgänge */
        get: operations["ev_api_v1_energy_ev_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/import/ha": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** HA-Recorder-Export (CSV, optional gzip) in Stundenbilanzen übernehmen */
        post: operations["import_ha_api_v1_import_ha_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/control/actuators/{key}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Aktor schalten */
        post: operations["switch_actuator_api_v1_control_actuators__key__post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/control/heat-pump/mode": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Betriebsmodus der Wärmepumpe setzen */
        post: operations["set_mode_api_v1_control_heat_pump_mode_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/control/decisions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Letzte Regler-Entscheidungen (Zustandswechsel) */
        get: operations["decisions_api_v1_control_decisions_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/config": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Aktive Regler- und Modellkonfiguration */
        get: operations["config_api_v1_config_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/demo": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Demo steuern: Zeitraffer, Störungen, Szenarien */
        post: operations["control_api_v1_demo_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** ActuatorCommandIn */
        ActuatorCommandIn: {
            /** State */
            state: boolean;
            /** Duration Min */
            duration_min?: number | null;
        };
        /** ActuatorCommandOut */
        ActuatorCommandOut: {
            /** Key */
            key: string;
            /** Requested */
            requested: boolean;
            /** Observed */
            observed: boolean | null;
            /** Ok */
            ok: boolean;
            /** Message De */
            message_de: string;
        };
        /**
         * AutoProfile
         * @enum {string}
         */
        AutoProfile: "eco" | "pv" | "price" | "smart";
        /** BalanceConfig */
        BalanceConfig: {
            /**
             * Tolerance Kw
             * @default 0.3
             */
            tolerance_kw: number;
            /**
             * Min Flow Kw
             * @default 0.05
             */
            min_flow_kw: number;
        };
        /** BatteryConfig */
        BatteryConfig: {
            /**
             * Capacity Kwh
             * @default 5.1
             */
            capacity_kwh: number;
            /**
             * Max Power Kw
             * @default 3.7
             */
            max_power_kw: number;
        };
        /** BinCorrection */
        BinCorrection: {
            /** Bin */
            bin: number;
            /** Label De */
            label_de: string;
            /**
             * Factor
             * @default 1
             */
            factor: number;
            /**
             * Previous
             * @default 1
             */
            previous: number;
            /** Last Ratio */
            last_ratio?: number | null;
            /**
             * Days
             * @default 0
             */
            days: number;
        };
        /** BlockRuleConfig */
        BlockRuleConfig: {
            /**
             * Enabled
             * @default false
             */
            enabled: boolean;
            /**
             * Max Duration Min
             * @default 120
             */
            max_duration_min: number;
            /**
             * Max Per Day
             * @default 2
             */
            max_per_day: number;
            /**
             * Min Soc
             * @default 0.6
             */
            min_soc: number;
            /**
             * Min Outdoor Temp C
             * @default 3
             */
            min_outdoor_temp_c: number;
            /**
             * Block Ttl Min
             * @default 15
             */
            block_ttl_min: number;
        };
        /** BufferConfig */
        BufferConfig: {
            /**
             * Volume Liters
             * @default 1000
             */
            volume_liters: number;
            /** Layers */
            layers?: number[];
            /**
             * Min Useful Temperature C
             * @default 35
             */
            min_useful_temperature_c: number;
            /**
             * Target Temperature C
             * @default 50
             */
            target_temperature_c: number;
            /**
             * Max Temperature C
             * @default 62
             */
            max_temperature_c: number;
            /**
             * Comfort Min Top C
             * @default 42
             */
            comfort_min_top_c: number;
            /**
             * Loss Kw Per K
             * @default 0.004
             */
            loss_kw_per_k: number;
            /**
             * Soc Method
             * @default layered_energy_v1
             * @enum {string}
             */
            soc_method: "layered_energy_v1" | "weighted_mean_v1";
            /** Weights */
            weights?: number[];
            /**
             * Status Thresholds
             * @default [
             *       0.2,
             *       0.6,
             *       0.9
             *     ]
             */
            status_thresholds: [
                number,
                number,
                number
            ];
            /**
             * Soc Full
             * @default 0.95
             */
            soc_full: number;
        };
        /** BufferState */
        BufferState: {
            /** Soc */
            soc: number | null;
            /** Usable Energy Kwh */
            usable_energy_kwh: number | null;
            /** Capacity Kwh */
            capacity_kwh: number;
            /** Volume Liters */
            volume_liters: number;
            /** Mean Temp C */
            mean_temp_c: number | null;
            status: components["schemas"]["BufferStatus"];
            /** Method */
            method: string;
            /** Headroom Soc */
            headroom_soc: number | null;
        };
        /**
         * BufferStatus
         * @enum {string}
         */
        BufferStatus: "cold" | "partial" | "warm" | "full" | "unknown";
        /** BufferTemperatures */
        BufferTemperatures: {
            top: components["schemas"]["Measurement"];
            mid_top: components["schemas"]["Measurement"];
            mid_bottom: components["schemas"]["Measurement"];
            bottom: components["schemas"]["Measurement"];
        };
        /** ControlConfig */
        ControlConfig: {
            /**
             * Tick S
             * @default 10
             */
            tick_s: number;
            /**
             * Ewma Seconds
             * @default 180
             */
            ewma_seconds: number;
            /**
             * Sensor Grace Min
             * @default 5
             */
            sensor_grace_min: number;
            /**
             * Max Toggles Per Hour
             * @default 4
             */
            max_toggles_per_hour: number;
            /**
             * Failsafe Hold Min
             * @default 60
             */
            failsafe_hold_min: number;
            /**
             * @default {
             *       "on_surplus_kw": 4,
             *       "off_import_kw": 1.5,
             *       "on_delay_min": 5,
             *       "off_delay_min": 10,
             *       "count_battery_charging_above_soc": 0.8,
             *       "heat_pump_before_ev": false,
             *       "min_buffer_headroom_soc": 0.1
             *     }
             */
            pv: components["schemas"]["PvRuleConfig"];
            /**
             * @default {
             *       "negative_price_release": true,
             *       "cheap_quantile": 0.1,
             *       "min_window_min": 30,
             *       "price_max_age_h": 30,
             *       "expensive_quantile": 0.85
             *     }
             */
            price: components["schemas"]["PriceRuleConfig"];
            /**
             * @default {
             *       "enabled": false,
             *       "max_duration_min": 120,
             *       "max_per_day": 2,
             *       "min_soc": 0.6,
             *       "min_outdoor_temp_c": 3,
             *       "block_ttl_min": 15
             *     }
             */
            block: components["schemas"]["BlockRuleConfig"];
        };
        /**
         * ControllerState
         * @enum {string}
         */
        ControllerState: "off" | "idle" | "arming" | "released" | "running_released" | "cooldown" | "manual" | "failsafe";
        /**
         * CorrectorState
         * @description Serialisierbarer Zustand des Korrektors (Persistenz in der API).
         */
        CorrectorState: {
            /** Bins */
            bins?: components["schemas"]["BinCorrection"][];
            /**
             * K Global
             * @default 1
             */
            k_global: number;
            /**
             * K Global Previous
             * @default 1
             */
            k_global_previous: number;
            /**
             * Days Learned
             * @default 0
             */
            days_learned: number;
            /**
             * Min Days
             * @default 14
             */
            min_days: number;
            /**
             * Half Life Days
             * @default 10
             */
            half_life_days: number;
            /** Updated On */
            updated_on?: string | null;
        };
        /** DailyScoreOut */
        DailyScoreOut: {
            /**
             * Day
             * Format: date
             */
            day: string;
            /** Energy Forecast Kwh */
            energy_forecast_kwh: number;
            /** Energy Actual Kwh */
            energy_actual_kwh: number;
            /** Energy Error Pct */
            energy_error_pct: number | null;
            /** Mae Kw */
            mae_kw: number;
            /** Bias Kw */
            bias_kw: number;
            /** K Global After */
            k_global_after: number;
            /** Issued At */
            issued_at?: string | null;
        };
        /** Decision */
        Decision: {
            /**
             * Id
             * Format: uuid
             */
            id?: string;
            /**
             * At
             * Format: date-time
             */
            at: string;
            controller_state: components["schemas"]["ControllerState"];
            /** K1 Release */
            k1_release: boolean;
            /** K2 Block */
            k2_block: boolean;
            /** Reasons */
            reasons: components["schemas"]["ReasonCode"][];
            /** Blocked By */
            blocked_by: components["schemas"]["ReasonCode"][];
            inputs: components["schemas"]["DecisionInputs"];
            /**
             * Valid Until
             * Format: date-time
             */
            valid_until: string;
            next_expected: components["schemas"]["NextExpected"] | null;
            /** Explanation De */
            explanation_de: string;
            /**
             * Changed
             * @default false
             */
            changed: boolean;
        };
        /** DecisionInputs */
        DecisionInputs: {
            /** Surplus Ewma Kw */
            surplus_ewma_kw: number | null;
            /** Import Ewma Kw */
            import_ewma_kw: number | null;
            /** Hp Running */
            hp_running: boolean;
            /** Hp Power Kw */
            hp_power_kw: number;
            /** Buffer Soc */
            buffer_soc: number | null;
            /** Buffer Top C */
            buffer_top_c: number | null;
            /** Price Ct Kwh */
            price_ct_kwh: number | null;
            /** Price Rank */
            price_rank: number | null;
            /** Outdoor Temp C */
            outdoor_temp_c: number | null;
            /** Starts Today */
            starts_today: number;
            /** Seconds Since Stop */
            seconds_since_stop: number | null;
            /** Seconds Since Start */
            seconds_since_start: number | null;
        };
        /** DemoControlIn */
        DemoControlIn: {
            /** Speed */
            speed?: number | null;
            /** Fault Key */
            fault_key?: string | null;
            /** Fault Quality */
            fault_quality?: ("stale" | "unavailable" | "unknown") | null;
            /** Fault Duration S */
            fault_duration_s?: number | null;
            /** Scenario */
            scenario?: ("reset" | "sunny_surplus" | "cold_evening" | "buffer_full" | "sensor_outage") | null;
        };
        /** EnergyBucketOut */
        EnergyBucketOut: {
            /**
             * Start
             * Format: date-time
             */
            start: string;
            /**
             * End
             * Format: date-time
             */
            end: string;
            /** Label */
            label: string;
            totals: components["schemas"]["EnergyTotalsOut"];
        };
        /** EnergyMetaOut */
        EnergyMetaOut: {
            /** Battery Capacity Kwh */
            battery_capacity_kwh: number;
            /** Feed In Ct Kwh */
            feed_in_ct_kwh: number;
            /** Data Since */
            data_since: string | null;
            /** Coverage */
            coverage: number | null;
            /** Estimated Note De */
            estimated_note_de: string;
        };
        /** EnergySnapshot */
        EnergySnapshot: {
            /**
             * Timestamp
             * Format: date-time
             */
            timestamp: string;
            pv_power_kw: components["schemas"]["Measurement"];
            grid_power_kw: components["schemas"]["Measurement"];
            battery_power_kw: components["schemas"]["Measurement"];
            battery_soc: components["schemas"]["Measurement"];
            house_power_kw: components["schemas"]["Measurement"];
            base_load_kw: components["schemas"]["Measurement"];
            heat_pump_power_kw: components["schemas"]["Measurement"];
            ev_power_kw: components["schemas"]["Measurement"];
            electricity_price_ct_kwh: components["schemas"]["Measurement"];
            outdoor_temp_c: components["schemas"]["Measurement"];
            buffer_temps_c: components["schemas"]["BufferTemperatures"];
            hp_release_contact: components["schemas"]["Measurement"];
            hp_block_contact: components["schemas"]["Measurement"];
            /** Actuators */
            actuators?: {
                [key: string]: components["schemas"]["Measurement"];
            };
            /**
             * Balance Residual Kw
             * @default 0
             */
            balance_residual_kw: number;
        };
        /** EnergySummaryOut */
        EnergySummaryOut: {
            /**
             * Period
             * @enum {string}
             */
            period: "day" | "week" | "month" | "year";
            /**
             * Anchor
             * Format: date
             */
            anchor: string;
            /**
             * Start
             * Format: date-time
             */
            start: string;
            /**
             * End
             * Format: date-time
             */
            end: string;
            totals: components["schemas"]["EnergyTotalsOut"];
            /** Buckets */
            buckets: components["schemas"]["EnergyBucketOut"][];
            meta: components["schemas"]["EnergyMetaOut"];
        };
        /**
         * EnergyTotalsOut
         * @description Summen plus abgeleitete Kennzahlen als normale Felder (für JSON).
         */
        EnergyTotalsOut: {
            /**
             * Minutes
             * @default 0
             */
            minutes: number;
            /**
             * Pv Kwh
             * @default 0
             */
            pv_kwh: number;
            /**
             * Import Kwh
             * @default 0
             */
            import_kwh: number;
            /**
             * Export Kwh
             * @default 0
             */
            export_kwh: number;
            /**
             * Battery Charge Kwh
             * @default 0
             */
            battery_charge_kwh: number;
            /**
             * Battery Discharge Kwh
             * @default 0
             */
            battery_discharge_kwh: number;
            /**
             * House Kwh
             * @default 0
             */
            house_kwh: number;
            /**
             * Heat Pump Kwh
             * @default 0
             */
            heat_pump_kwh: number;
            /**
             * Ev Kwh
             * @default 0
             */
            ev_kwh: number;
            /**
             * Base Kwh
             * @default 0
             */
            base_kwh: number;
            /**
             * Pv Direct Kwh
             * @default 0
             */
            pv_direct_kwh: number;
            /**
             * Battery To House Kwh
             * @default 0
             */
            battery_to_house_kwh: number;
            /**
             * Grid To House Kwh
             * @default 0
             */
            grid_to_house_kwh: number;
            /**
             * Pv To Battery Kwh
             * @default 0
             */
            pv_to_battery_kwh: number;
            /**
             * Grid To Battery Kwh
             * @default 0
             */
            grid_to_battery_kwh: number;
            /**
             * Heat Pump Pv Kwh
             * @default 0
             */
            heat_pump_pv_kwh: number;
            /**
             * Heat Pump Battery Kwh
             * @default 0
             */
            heat_pump_battery_kwh: number;
            /**
             * Heat Pump Grid Kwh
             * @default 0
             */
            heat_pump_grid_kwh: number;
            /**
             * Ev Pv Kwh
             * @default 0
             */
            ev_pv_kwh: number;
            /**
             * Ev Battery Kwh
             * @default 0
             */
            ev_battery_kwh: number;
            /**
             * Ev Grid Kwh
             * @default 0
             */
            ev_grid_kwh: number;
            /**
             * Import Cost Eur
             * @default 0
             */
            import_cost_eur: number;
            /**
             * Export Revenue Eur
             * @default 0
             */
            export_revenue_eur: number;
            /**
             * Heat Pump Cost Eur
             * @default 0
             */
            heat_pump_cost_eur: number;
            /**
             * Heat Pump Opportunity Eur
             * @default 0
             */
            heat_pump_opportunity_eur: number;
            /**
             * Ev Cost Eur
             * @default 0
             */
            ev_cost_eur: number;
            /**
             * Ev Opportunity Eur
             * @default 0
             */
            ev_opportunity_eur: number;
            /**
             * Battery Savings Eur
             * @default 0
             */
            battery_savings_eur: number;
            /**
             * Pv Direct Savings Eur
             * @default 0
             */
            pv_direct_savings_eur: number;
            /**
             * Price Weighted Ct
             * @default 0
             */
            price_weighted_ct: number;
            /**
             * Price Missing Minutes
             * @default 0
             */
            price_missing_minutes: number;
            /** Autarky */
            autarky?: number | null;
            /** Self Consumption Share */
            self_consumption_share?: number | null;
            /** Avg Import Price Ct */
            avg_import_price_ct?: number | null;
        };
        /** EvReportOut */
        EvReportOut: {
            summary: components["schemas"]["EnergySummaryOut"];
            /** Sessions */
            sessions: components["schemas"]["EvSessionOut"][];
        };
        /** EvSessionOut */
        EvSessionOut: {
            /**
             * Start
             * Format: date-time
             */
            start: string;
            /**
             * End
             * Format: date-time
             */
            end: string;
            /** Kwh */
            kwh: number;
            /** Pv Share */
            pv_share: number | null;
            /** Grid Kwh */
            grid_kwh: number;
            /** Cost Eur */
            cost_eur: number;
            /** Avg Kw */
            avg_kw: number;
        };
        /** ForecastDayOut */
        ForecastDayOut: {
            /**
             * Day
             * Format: date
             */
            day: string;
            /** Issued At */
            issued_at: string | null;
            score: components["schemas"]["ForecastScore"] | null;
            /** Points */
            points: components["schemas"]["ForecastPointOut"][];
        };
        /** ForecastEvaluationOut */
        ForecastEvaluationOut: {
            /**
             * Generated At
             * Format: date-time
             */
            generated_at: string;
            /** Stage De */
            stage_de: string;
            /** Sources */
            sources: components["schemas"]["SourceOut"][];
            today: components["schemas"]["ForecastDayOut"];
            yesterday: components["schemas"]["ForecastDayOut"];
            /** Daily */
            daily: components["schemas"]["DailyScoreOut"][];
            /** Horizons */
            horizons: components["schemas"]["HorizonScoreOut"][];
            corrector: components["schemas"]["CorrectorState"];
            /** Correction Active */
            correction_active: boolean;
            /** Next Changes De */
            next_changes_de: string[];
            /** Runs Kept */
            runs_kept: number;
            /** Notes De */
            notes_de: string[];
        };
        /** ForecastPointOut */
        ForecastPointOut: {
            /**
             * Ts
             * Format: date-time
             */
            ts: string;
            /** Actual Kw */
            actual_kw: number | null;
            /** Day Ahead Kw */
            day_ahead_kw: number | null;
            /** Latest Kw */
            latest_kw: number | null;
            /** Corrected Kw */
            corrected_kw: number | null;
        };
        /** ForecastScore */
        ForecastScore: {
            /** N */
            n: number;
            /** Mae Kw */
            mae_kw: number;
            /** Bias Kw */
            bias_kw: number;
            /** Rmse Kw */
            rmse_kw: number;
            /** Energy Forecast Kwh */
            energy_forecast_kwh: number;
            /** Energy Actual Kwh */
            energy_actual_kwh: number;
            /** Energy Error Pct */
            energy_error_pct: number | null;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * HeatDemandConfig
         * @description Wärmebedarfsmodell v1 (Plan 20.2): Heizgradstunden, Warmwasserprofil, COP-Kennlinie.
         */
        HeatDemandConfig: {
            /**
             * Heat Loss Kw Per K
             * @default 0.22
             */
            heat_loss_kw_per_k: number;
            /**
             * Indoor Target C
             * @default 21
             */
            indoor_target_c: number;
            /**
             * Heating Limit C
             * @default 15
             */
            heating_limit_c: number;
            /**
             * Internal Gains Kw
             * @default 0.4
             */
            internal_gains_kw: number;
            /**
             * Dhw Kwh Per Day
             * @default 8
             */
            dhw_kwh_per_day: number;
            /** Dhw Profile */
            dhw_profile?: number[];
            /** Cop Curve */
            cop_curve?: [
                number,
                number
            ][];
        };
        /** HeatForecastPoint */
        HeatForecastPoint: {
            /**
             * Ts
             * Format: date-time
             */
            ts: string;
            /** Outdoor C */
            outdoor_c: number;
            /** Heating Kw */
            heating_kw: number;
            /** Dhw Kw */
            dhw_kw: number;
            /** Cop */
            cop: number;
            /** Electric Kw */
            electric_kw: number;
        };
        /** HeatPumpConfig */
        HeatPumpConfig: {
            /**
             * Minimum Electric Power Kw
             * @default 3.5
             */
            minimum_electric_power_kw: number;
            /**
             * Nominal Electric Power Kw
             * @default 4.5
             */
            nominal_electric_power_kw: number;
            /**
             * Nominal Thermal Power Kw
             * @default 12
             */
            nominal_thermal_power_kw: number;
            /**
             * Running Threshold Kw
             * @default 0.5
             */
            running_threshold_kw: number;
            /**
             * Running Debounce S
             * @default 60
             */
            running_debounce_s: number;
            /**
             * Min Runtime Min
             * @default 30
             */
            min_runtime_min: number;
            /**
             * Min Offtime Min
             * @default 20
             */
            min_offtime_min: number;
            /**
             * Start Timeout Min
             * @default 10
             */
            start_timeout_min: number;
            /**
             * Max Starts Per Day
             * @default 8
             */
            max_starts_per_day: number;
            /**
             * Release Ttl Min
             * @default 20
             */
            release_ttl_min: number;
            /**
             * Hw Auto Off Release S
             * @default 1800
             */
            hw_auto_off_release_s: number;
            /**
             * Hw Auto Off Block S
             * @default 1200
             */
            hw_auto_off_block_s: number;
        };
        /** HeatPumpModeIn */
        HeatPumpModeIn: {
            system_mode: components["schemas"]["SystemMode"];
            auto_profile?: components["schemas"]["AutoProfile"] | null;
            /** Manual State */
            manual_state?: ("on" | "off") | null;
            /**
             * Duration Min
             * @default 120
             */
            duration_min: number;
        };
        /** HeatPumpState */
        HeatPumpState: {
            /** Running */
            running: boolean;
            /** Running Since */
            running_since: string | null;
            /** Stopped Since */
            stopped_since: string | null;
            /** Power Kw */
            power_kw: number;
            /** Release Contact On */
            release_contact_on: boolean;
            /** Block Contact On */
            block_contact_on: boolean;
            /** Starts Today */
            starts_today: number;
            /**
             * Power Known
             * @default true
             */
            power_known: boolean;
        };
        /** HeatReportOut */
        HeatReportOut: {
            summary: components["schemas"]["EnergySummaryOut"];
            /** Thermal Kwh Est */
            thermal_kwh_est: number;
            /** Cop Est */
            cop_est: number;
            /** Forecast */
            forecast: components["schemas"]["HeatForecastPoint"][];
            /** Forecast Electric Kwh 24H */
            forecast_electric_kwh_24h: number;
            /** Forecast Thermal Kwh 24H */
            forecast_thermal_kwh_24h: number;
            /** Buffer Series */
            buffer_series: {
                [key: string]: number | string | null;
            }[];
            /** Heat Loss Kw Per K */
            heat_loss_kw_per_k: number;
            /** Model Note De */
            model_note_de: string;
        };
        /** HemsConfig */
        HemsConfig: {
            /**
             * @default {
             *       "minimum_electric_power_kw": 3.5,
             *       "nominal_electric_power_kw": 4.5,
             *       "nominal_thermal_power_kw": 12,
             *       "running_threshold_kw": 0.5,
             *       "running_debounce_s": 60,
             *       "min_runtime_min": 30,
             *       "min_offtime_min": 20,
             *       "start_timeout_min": 10,
             *       "max_starts_per_day": 8,
             *       "release_ttl_min": 20,
             *       "hw_auto_off_release_s": 1800,
             *       "hw_auto_off_block_s": 1200
             *     }
             */
            heat_pump: components["schemas"]["HeatPumpConfig"];
            /**
             * @default {
             *       "tick_s": 10,
             *       "ewma_seconds": 180,
             *       "sensor_grace_min": 5,
             *       "max_toggles_per_hour": 4,
             *       "failsafe_hold_min": 60,
             *       "pv": {
             *         "count_battery_charging_above_soc": 0.8,
             *         "heat_pump_before_ev": false,
             *         "min_buffer_headroom_soc": 0.1,
             *         "off_delay_min": 10,
             *         "off_import_kw": 1.5,
             *         "on_delay_min": 5,
             *         "on_surplus_kw": 4
             *       },
             *       "price": {
             *         "cheap_quantile": 0.1,
             *         "expensive_quantile": 0.85,
             *         "min_window_min": 30,
             *         "negative_price_release": true,
             *         "price_max_age_h": 30
             *       },
             *       "block": {
             *         "block_ttl_min": 15,
             *         "enabled": false,
             *         "max_duration_min": 120,
             *         "max_per_day": 2,
             *         "min_outdoor_temp_c": 3,
             *         "min_soc": 0.6
             *       }
             *     }
             */
            control: components["schemas"]["ControlConfig"];
            /**
             * @default {
             *       "volume_liters": 1000,
             *       "layers": [
             *         0.25,
             *         0.25,
             *         0.25,
             *         0.25
             *       ],
             *       "min_useful_temperature_c": 35,
             *       "target_temperature_c": 50,
             *       "max_temperature_c": 62,
             *       "comfort_min_top_c": 42,
             *       "loss_kw_per_k": 0.004,
             *       "soc_method": "layered_energy_v1",
             *       "weights": [
             *         0.25,
             *         0.25,
             *         0.25,
             *         0.25
             *       ],
             *       "status_thresholds": [
             *         0.2,
             *         0.6,
             *         0.9
             *       ],
             *       "soc_full": 0.95
             *     }
             */
            buffer: components["schemas"]["BufferConfig"];
            /**
             * @default {
             *       "tolerance_kw": 0.3,
             *       "min_flow_kw": 0.05
             *     }
             */
            balance: components["schemas"]["BalanceConfig"];
            /**
             * @default {
             *       "power_s": 180,
             *       "battery_s": 180,
             *       "temperature_s": 900,
             *       "price_s": 7200
             *     }
             */
            timeouts: components["schemas"]["SensorTimeouts"];
            /**
             * @default {
             *       "feed_in_ct_kwh": 8,
             *       "fallback_import_ct_kwh": 30
             *     }
             */
            tariff: components["schemas"]["TariffConfig"];
            /**
             * @default {
             *       "heat_loss_kw_per_k": 0.22,
             *       "indoor_target_c": 21,
             *       "heating_limit_c": 15,
             *       "internal_gains_kw": 0.4,
             *       "dhw_kwh_per_day": 8,
             *       "dhw_profile": [
             *         0.2,
             *         0.1,
             *         0.1,
             *         0.1,
             *         0.2,
             *         0.6,
             *         1.6,
             *         2.2,
             *         1.8,
             *         1,
             *         0.8,
             *         0.8,
             *         0.9,
             *         0.7,
             *         0.6,
             *         0.6,
             *         0.8,
             *         1.2,
             *         1.8,
             *         2,
             *         1.6,
             *         1,
             *         0.6,
             *         0.3
             *       ],
             *       "cop_curve": [
             *         [
             *           -7,
             *           2.4
             *         ],
             *         [
             *           2,
             *           3
             *         ],
             *         [
             *           7,
             *           3.5
             *         ],
             *         [
             *           15,
             *           4.2
             *         ]
             *       ]
             *     }
             */
            heat_demand: components["schemas"]["HeatDemandConfig"];
            /**
             * @default {
             *       "capacity_kwh": 5.1,
             *       "max_power_kw": 3.7
             *     }
             */
            battery: components["schemas"]["BatteryConfig"];
        };
        /** HistoryOut */
        HistoryOut: {
            /**
             * Start
             * Format: date-time
             */
            start: string;
            /**
             * End
             * Format: date-time
             */
            end: string;
            /**
             * Resolution S
             * @default 60
             */
            resolution_s: number;
            /** Rows */
            rows: {
                [key: string]: number | string | null;
            }[];
        };
        /** HorizonScoreOut */
        HorizonScoreOut: {
            /** Key */
            key: string;
            /** Label De */
            label_de: string;
            score: components["schemas"]["ForecastScore"];
        };
        /** ImportResult */
        ImportResult: {
            /** Kind */
            kind: string;
            /** Rows */
            rows: number;
            /** Entities */
            entities: string[];
            /** Unmapped */
            unmapped: string[];
            /** First */
            first: string | null;
            /** Last */
            last: string | null;
            /** Hours Computed */
            hours_computed: number;
            /** Hours Written */
            hours_written: number;
            /** Hours Kept Existing */
            hours_kept_existing: number;
            /** Raw Readings Stored */
            raw_readings_stored: number;
            /** Price Minutes From Tibber */
            price_minutes_from_tibber: number;
            /** Minutes Without Price */
            minutes_without_price: number;
            /** Dry Run */
            dry_run: boolean;
            /** Note De */
            note_de: string;
        };
        /** LiveStateOut */
        LiveStateOut: {
            snapshot: components["schemas"]["EnergySnapshot"];
            buffer: components["schemas"]["BufferState"];
            heat_pump: components["schemas"]["HeatPumpState"];
            decision: components["schemas"]["Decision"] | null;
            operating_mode: components["schemas"]["OperatingMode"];
            /** Price Rank */
            price_rank: number | null;
            /** Today Kwh */
            today_kwh: {
                [key: string]: number;
            };
            system: components["schemas"]["SystemStatusOut"];
        };
        /** Measurement */
        Measurement: {
            /** Value */
            value: number | null;
            /**
             * Observed At
             * Format: date-time
             */
            observed_at: string;
            quality: components["schemas"]["Quality"];
            /** Source */
            source: string;
        };
        /** NextExpected */
        NextExpected: {
            /** Action */
            action: string;
            /** At */
            at: string | null;
            because: components["schemas"]["ReasonCode"];
            /** Text De */
            text_de: string;
        };
        /** OperatingMode */
        OperatingMode: {
            /** @default auto */
            system_mode: components["schemas"]["SystemMode"];
            /** @default smart */
            auto_profile: components["schemas"]["AutoProfile"];
            override?: components["schemas"]["Override"] | null;
        };
        /** Override */
        Override: {
            kind: components["schemas"]["OverrideKind"];
            /**
             * Started At
             * Format: date-time
             */
            started_at: string;
            /**
             * Ends At
             * Format: date-time
             */
            ends_at: string;
            /**
             * Set By
             * @default dashboard
             */
            set_by: string;
        };
        /**
         * OverrideKind
         * @enum {string}
         */
        OverrideKind: "force_release" | "force_off" | "force_block";
        /** PlanIntervalOut */
        PlanIntervalOut: {
            /**
             * Ts
             * Format: date-time
             */
            ts: string;
            /** Expected Pv Kw */
            expected_pv_kw: number;
            /** Price Ct Kwh */
            price_ct_kwh: number | null;
            /**
             * Planned Hp State
             * @enum {string}
             */
            planned_hp_state: "off" | "release" | "free" | "avoid";
            /** Reason Code */
            reason_code: string;
            /** Note De */
            note_de?: string | null;
        };
        /** PlanOut */
        PlanOut: {
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Planner */
            planner: string;
            /**
             * Horizon Start
             * Format: date-time
             */
            horizon_start: string;
            /**
             * Horizon End
             * Format: date-time
             */
            horizon_end: string;
            /** Windows */
            windows: components["schemas"]["PriceWindowOut"][];
            /** Intervals */
            intervals: components["schemas"]["PlanIntervalOut"][];
            /** Pv Forecast Today Kwh */
            pv_forecast_today_kwh: number;
            next_cheap_window: components["schemas"]["PriceWindowOut"] | null;
        };
        /** PriceRuleConfig */
        PriceRuleConfig: {
            /**
             * Negative Price Release
             * @default true
             */
            negative_price_release: boolean;
            /**
             * Cheap Quantile
             * @default 0.1
             */
            cheap_quantile: number;
            /**
             * Min Window Min
             * @default 30
             */
            min_window_min: number;
            /**
             * Price Max Age H
             * @default 30
             */
            price_max_age_h: number;
            /**
             * Expensive Quantile
             * @default 0.85
             */
            expensive_quantile: number;
        };
        /** PriceWindowOut */
        PriceWindowOut: {
            /**
             * Start
             * Format: date-time
             */
            start: string;
            /**
             * End
             * Format: date-time
             */
            end: string;
            /**
             * Kind
             * @enum {string}
             */
            kind: "cheap" | "expensive" | "negative" | "pv_surplus";
            /** Avg Ct Kwh */
            avg_ct_kwh?: number | null;
            /** Label De */
            label_de: string;
        };
        /** PvRuleConfig */
        PvRuleConfig: {
            /**
             * On Surplus Kw
             * @default 4
             */
            on_surplus_kw: number;
            /**
             * Off Import Kw
             * @default 1.5
             */
            off_import_kw: number;
            /**
             * On Delay Min
             * @default 5
             */
            on_delay_min: number;
            /**
             * Off Delay Min
             * @default 10
             */
            off_delay_min: number;
            /**
             * Count Battery Charging Above Soc
             * @default 0.8
             */
            count_battery_charging_above_soc: number;
            /**
             * Heat Pump Before Ev
             * @default false
             */
            heat_pump_before_ev: boolean;
            /**
             * Min Buffer Headroom Soc
             * @default 0.1
             */
            min_buffer_headroom_soc: number;
        };
        /**
         * Quality
         * @enum {string}
         */
        Quality: "ok" | "stale" | "unavailable" | "unknown" | "derived" | "inconsistent";
        /**
         * ReasonCode
         * @enum {string}
         */
        ReasonCode: "pv_surplus" | "pv_surplus_fading" | "price_negative" | "price_cheap_window" | "planned_window" | "heat_demand_forced" | "hp_running_own_control" | "min_runtime_hold" | "min_offtime_pending" | "on_delay_pending" | "off_delay_pending" | "buffer_full" | "buffer_no_headroom" | "max_starts_reached" | "no_trigger" | "import_too_high" | "manual_override" | "mode_off" | "sensor_stale" | "sensor_unavailable" | "price_data_stale" | "hp_not_responding" | "failsafe" | "toggle_rate_exceeded";
        /** SensorTimeouts */
        SensorTimeouts: {
            /**
             * Power S
             * @default 180
             */
            power_s: number;
            /**
             * Battery S
             * @default 180
             */
            battery_s: number;
            /**
             * Temperature S
             * @default 900
             */
            temperature_s: number;
            /**
             * Price S
             * @default 7200
             */
            price_s: number;
        };
        /** SourceOut */
        SourceOut: {
            /** Name */
            name: string;
            /** Label De */
            label_de: string;
            /** Weight */
            weight: number;
            /** Mae 7D Kw */
            mae_7d_kw: number | null;
            /** Active */
            active: boolean;
        };
        /**
         * SourceStatusOut
         * @description Zustand einer Messquelle (Bridge, myenergi, …).
         */
        SourceStatusOut: {
            /** Name */
            name: string;
            /** Online */
            online: boolean;
            /** Last Ok */
            last_ok?: string | null;
            /**
             * Detail De
             * @default
             */
            detail_de: string;
        };
        /**
         * SystemMode
         * @enum {string}
         */
        SystemMode: "off" | "manual" | "auto";
        /** SystemStatusOut */
        SystemStatusOut: {
            /** Mode */
            mode: string;
            /**
             * Server Time
             * Format: date-time
             */
            server_time: string;
            /** Sim Speed */
            sim_speed: number;
            /** Bridge Online */
            bridge_online: boolean;
            /** Sse Clients */
            sse_clients: number;
            /** Version */
            version: string;
            /** Connection Label De */
            connection_label_de: string;
            /** Sources */
            sources?: components["schemas"]["SourceStatusOut"][];
        };
        /**
         * TariffConfig
         * @description Geldseite: Einspeisevergütung und Ersatzpreis, falls kein Tibber-Preis vorliegt.
         */
        TariffConfig: {
            /**
             * Feed In Ct Kwh
             * @default 8
             */
            feed_in_ct_kwh: number;
            /**
             * Fallback Import Ct Kwh
             * @default 30
             */
            fallback_import_ct_kwh: number;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    state_api_v1_live_state_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LiveStateOut"];
                };
            };
        };
    };
    stream_api_v1_live_stream_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    history_api_v1_history_get: {
        parameters: {
            query?: {
                range?: "today" | "yesterday" | "24h" | "custom";
                start?: string | null;
                end?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HistoryOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    plan_api_v1_plan_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlanOut"];
                };
            };
        };
    };
    evaluation_api_v1_forecast_evaluation_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ForecastEvaluationOut"];
                };
            };
        };
    };
    summary_api_v1_energy_summary_get: {
        parameters: {
            query?: {
                period?: "day" | "week" | "month" | "year";
                anchor?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EnergySummaryOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    heat_api_v1_energy_heat_get: {
        parameters: {
            query?: {
                period?: "day" | "week" | "month" | "year";
                anchor?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HeatReportOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    ev_api_v1_energy_ev_get: {
        parameters: {
            query?: {
                period?: "day" | "week" | "month" | "year";
                anchor?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EvReportOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    import_ha_api_v1_import_ha_post: {
        parameters: {
            query?: {
                kind?: "auto" | "states" | "statistics";
                dry_run?: boolean;
                /** @description JSON {entity: {key, unit?, sign?, scale?}} */
                extra_map?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ImportResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    switch_actuator_api_v1_control_actuators__key__post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                key: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ActuatorCommandIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ActuatorCommandOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    set_mode_api_v1_control_heat_pump_mode_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["HeatPumpModeIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OperatingMode"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    decisions_api_v1_control_decisions_get: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Decision"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    config_api_v1_config_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HemsConfig"];
                };
            };
        };
    };
    control_api_v1_demo_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DemoControlIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
