"""phase 2 grundschema

Revision ID: 440a3f9346c1
Revises:
Create Date: 2026-09-04 21:10:48.299861+00:00
"""

from __future__ import annotations

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision = "440a3f9346c1"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "bridge_credentials",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=64), nullable=False),
        sa.Column("token_hash", sa.String(length=128), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("last_seen_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("token_hash"),
    )
    op.create_table(
        "bridge_sessions",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("bridge_id", sa.String(length=64), nullable=False),
        sa.Column("connected_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("disconnected_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("remote_version", sa.String(length=32), nullable=False),
        sa.Column("clock_offset_ms", sa.Integer(), nullable=False),
        sa.Column("frames_in", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "config_versions",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("created_by", sa.String(length=64), nullable=False),
        sa.Column("kind", sa.String(length=16), nullable=False),
        sa.Column(
            "payload", sa.JSON().with_variant(postgresql.JSONB(), "postgresql"), nullable=False
        ),
        sa.Column("comment", sa.Text(), nullable=True),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("config_versions", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_config_versions_active"), ["active"], unique=False)
        batch_op.create_index(batch_op.f("ix_config_versions_kind"), ["kind"], unique=False)

    op.create_table(
        "control_decisions",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("controller_state", sa.String(length=32), nullable=False),
        sa.Column("k1_release", sa.Boolean(), nullable=False),
        sa.Column("k2_block", sa.Boolean(), nullable=False),
        sa.Column(
            "reasons", sa.JSON().with_variant(postgresql.JSONB(), "postgresql"), nullable=False
        ),
        sa.Column(
            "blocked_by", sa.JSON().with_variant(postgresql.JSONB(), "postgresql"), nullable=False
        ),
        sa.Column(
            "inputs", sa.JSON().with_variant(postgresql.JSONB(), "postgresql"), nullable=False
        ),
        sa.Column("valid_until", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "next_expected", sa.JSON().with_variant(postgresql.JSONB(), "postgresql"), nullable=True
        ),
        sa.Column("explanation_de", sa.Text(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("control_decisions", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_control_decisions_at"), ["at"], unique=False)

    op.create_table(
        "forecast_runs",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("kind", sa.String(length=16), nullable=False),
        sa.Column("provider", sa.String(length=32), nullable=False),
        sa.Column("issued_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("horizon_start", sa.DateTime(timezone=True), nullable=False),
        sa.Column("horizon_end", sa.DateTime(timezone=True), nullable=False),
        sa.Column("resolution_min", sa.Integer(), nullable=False),
        sa.Column(
            "params", sa.JSON().with_variant(postgresql.JSONB(), "postgresql"), nullable=False
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("forecast_runs", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_forecast_runs_issued_at"), ["issued_at"], unique=False)
        batch_op.create_index(batch_op.f("ix_forecast_runs_kind"), ["kind"], unique=False)

    op.create_table(
        "kiosk_devices",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=64), nullable=False),
        sa.Column("paired_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("last_seen_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("session_token_hash", sa.String(length=128), nullable=False),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("session_token_hash"),
    )
    op.create_table(
        "live_state",
        sa.Column("sensor_key", sa.String(length=64), nullable=False),
        sa.Column("value", sa.Float(), nullable=True),
        sa.Column("observed_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("quality", sa.String(length=16), nullable=False),
        sa.Column("source", sa.String(length=128), nullable=False),
        sa.Column("received_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("sensor_key"),
    )
    op.create_table(
        "measurements_1min",
        sa.Column("sensor_key", sa.String(length=64), nullable=False),
        sa.Column("bucket", sa.DateTime(timezone=True), nullable=False),
        sa.Column("avg", sa.Float(), nullable=True),
        sa.Column("min", sa.Float(), nullable=True),
        sa.Column("max", sa.Float(), nullable=True),
        sa.Column("samples", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("sensor_key", "bucket"),
    )
    op.create_table(
        "measurements_raw",
        sa.Column("sensor_key", sa.String(length=64), nullable=False),
        sa.Column("observed_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("value", sa.Float(), nullable=True),
        sa.Column("quality", sa.SmallInteger(), nullable=False),
        sa.PrimaryKeyConstraint("sensor_key", "observed_at"),
    )
    with op.batch_alter_table("measurements_raw", schema=None) as batch_op:
        batch_op.create_index("ix_measurements_raw_observed_at", ["observed_at"], unique=False)

    op.create_table(
        "system_events",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("severity", sa.String(length=8), nullable=False),
        sa.Column("code", sa.String(length=64), nullable=False),
        sa.Column("message", sa.Text(), nullable=False),
        sa.Column(
            "context", sa.JSON().with_variant(postgresql.JSONB(), "postgresql"), nullable=False
        ),
        sa.Column("acknowledged_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("system_events", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_system_events_at"), ["at"], unique=False)
        batch_op.create_index(batch_op.f("ix_system_events_code"), ["code"], unique=False)

    op.create_table(
        "system_modes",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("system_mode", sa.String(length=8), nullable=False),
        sa.Column("auto_profile", sa.String(length=8), nullable=False),
        sa.Column(
            "override", sa.JSON().with_variant(postgresql.JSONB(), "postgresql"), nullable=True
        ),
        sa.Column("set_by", sa.String(length=64), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("system_modes", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_system_modes_at"), ["at"], unique=False)

    op.create_table(
        "actuator_commands",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("actuator_key", sa.String(length=64), nullable=False),
        sa.Column("desired_state", sa.Boolean(), nullable=False),
        sa.Column("ttl_s", sa.Integer(), nullable=True),
        sa.Column("decision_id", sa.Uuid(), nullable=True),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("sent_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("acked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("observed_state", sa.Boolean(), nullable=True),
        sa.Column("error", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(
            ["decision_id"],
            ["control_decisions.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("actuator_commands", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_actuator_commands_at"), ["at"], unique=False)

    op.create_table(
        "forecast_points",
        sa.Column("run_id", sa.Uuid(), nullable=False),
        sa.Column("ts", sa.DateTime(timezone=True), nullable=False),
        sa.Column("variable", sa.String(length=24), nullable=False),
        sa.Column("value", sa.Float(), nullable=True),
        sa.Column("value_lo", sa.Float(), nullable=True),
        sa.Column("value_hi", sa.Float(), nullable=True),
        sa.ForeignKeyConstraint(["run_id"], ["forecast_runs.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("run_id", "ts", "variable"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("forecast_points")
    with op.batch_alter_table("actuator_commands", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_actuator_commands_at"))

    op.drop_table("actuator_commands")
    with op.batch_alter_table("system_modes", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_system_modes_at"))

    op.drop_table("system_modes")
    with op.batch_alter_table("system_events", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_system_events_code"))
        batch_op.drop_index(batch_op.f("ix_system_events_at"))

    op.drop_table("system_events")
    with op.batch_alter_table("measurements_raw", schema=None) as batch_op:
        batch_op.drop_index("ix_measurements_raw_observed_at")

    op.drop_table("measurements_raw")
    op.drop_table("measurements_1min")
    op.drop_table("live_state")
    op.drop_table("kiosk_devices")
    with op.batch_alter_table("forecast_runs", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_forecast_runs_kind"))
        batch_op.drop_index(batch_op.f("ix_forecast_runs_issued_at"))

    op.drop_table("forecast_runs")
    with op.batch_alter_table("control_decisions", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_control_decisions_at"))

    op.drop_table("control_decisions")
    with op.batch_alter_table("config_versions", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_config_versions_kind"))
        batch_op.drop_index(batch_op.f("ix_config_versions_active"))

    op.drop_table("config_versions")
    op.drop_table("bridge_sessions")
    op.drop_table("bridge_credentials")
    # ### end Alembic commands ###
